# Generated by Django 3.1 on 2020-08-31 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=50, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=50)),
                ('ponto_referencia', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(blank=True, default=datetime.datetime.today, null=True)),
            ],
        ),
    ]
